name: movie_bloc_retrofit
description: Simple Movie App with BLOC + Retrofit

publish_to:
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  dio: 3.0.10
  shimmer: ^1.1.1
  flutter_bloc: ^6.0.1
  equatable: ^1.2.3
  retrofit: any
  json_serializable: ^3.3.0
  logger: any
  cached_network_image: ^2.2.0+1
  flutter_svg: ^0.20.0-nullsafety.3
  date_format: ^1.0.8
  sqflite: ^1.3.1+1
  path_provider: ^1.3.0
  curved_navigation_bar: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: any
  build_runner: any

dependency_overrides:
  analyzer: '0.39.14'

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
